/* this file automatically generated by the Makefile */
#define COMPILER "gcc"
#define OPTIMIZE ""
#define CFLAGS   "-D__USE_FIXED_PROTOTYPES__ -g -DDEBUG -DDEBUG_MACRO -rdynamic "
#define OBJDIR   "obj"
