{
  "__LOCALS_IN_TRACEBACK__", "",
  "__ARRAY_RESERVED_WORD__", "",
  "__CFG_MAX_LOCAL_VARIABLES__", "25",
  "__DEFAULT_DB__", "USE_MYSQL",
  "__CALLOUT_HANDLES__", "",
  "__SAVE_EXTENSION__", "\".o\"",
  "__DEFAULT_PRAGMAS__", "PRAGMA_WARNINGS + PRAGMA_STRICT_TYPES + PRAGMA_ERROR_CONTEXT + PRAGMA_OPTIMIZE + PRAGMA_SAVE_TYPES",
  "__BSDMALLOC__", "",
  "__CONFIG_FILE_DIR__", "\"/u/tim/COMP/bin\"",
  "__DO_MSTATS__", "",
  "__USE_32BIT_ADDRESSES__", "",
  "__HEARTBEAT_INTERVAL__", "2000000",
  "__NO_LIGHT__", "",
  "__RESTRICTED_ED__", "",
  "__ARRAY_STATS__", "",
  "__ARGUMENTS_IN_TRACEBACK__", "",
  "__AUTO_TRUST_BACKBONE__", "",
  "__SMALL_STRING_SIZE__", "100",
  "__HEART_BEAT_CHUNK__", "32",
  "__PACKAGE_CONTRIB__", "",
  "__PACKAGE_DB__", "",
  "__FLUSH_OUTPUT_IMMEDIATELY__", "",
  "__RUNTIME_LOADING__", "",
  "__CACHE_STATS__", "",
  "__LARGE_STRING_SIZE__", "1000",
  "__APPLY_CACHE_BITS__", "12",
  "__BINARIES__", "",
  "__STRING_STATS__", "",
  "__NO_ANSI__", "",
  "__SANE_EXPLODE_STRING__", "",
  "__CFG_MAX_CALL_DEPTH__", "50",
  "__LOG_CATCHES__", "",
  "__MAX_SAVE_SVALUE_DEPTH__", "25",
  "__MUDLIB_ERROR_HANDLER__", "",
  "__CFG_EVALUATOR_STACK_SIZE__", "1000",
  "__CALLOUT_CYCLE_SIZE__", "32",
  "__LPC_TO_C__", "",
  "__PACKAGE_SOCKETS__", "",
  "__CFG_LIVING_HASH_SIZE__", "1024",
  "__TRACE_CODE__", "",
  "__THIS_PLAYER_IN_CALL_OUT__", "",
  "__NONINTERACTIVE_STDERR_WRITE__", "",
  "__REF_RESERVED_WORD__", "",
  "__MESSAGE_BUFFER_SIZE__", "4096",
  "__TRACE__", "",
  "__STRIP_BEFORE_PROCESS_INPUT__", "",
  "__USE_MYSQL__", "2",
  "__NEXT_MALLOC_DEBUG__", "",
  "__PROFILE_FUNCTIONS__", "",
  "__TRAP_CRASHES__", "",
  "__DEBUGMALLOC__", "",
  "__LARGEST_PRINTABLE_STRING__", "8192",
  "__OPCPROF__", "",
  "__CUSTOM_CRYPT__", "",
  "__PACKAGE_DEVELOP__", "",
  "__PRIVS__", "",
  "__PACKAGE_MATRIX__", "",
  "__PACKAGE_MATH__", "",
  "__SENSIBLE_MODIFIERS__", "",
  "__PACKAGE_PARSER__", "",
  "__NO_WIZARDS__", "",
};

#define NUM_OPTION_DEFS 61

