
#ifndef PARSER_ERRORS_H
#define PARSER_ERRORS_H

#define PARSE_NOT_HERE 		1
#define	PARSE_NOT_ALIVE		2
#define	PARSE_UNACCESSIBLE	3
#define	PARSE_AMBIGUOUS		4
#define	PARSE_WRONG_NUMBER	5
#define	PARSE_ALLOCATED		6
#define	PARSE_NOT_FOUND		7		
#define	PARSE_TOO_MANY		8

#endif /* PARSER_ERRORS_H */
